package com.capstone.percs.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.capstone.percs.entities.Business;
import com.capstone.percs.entities.Promotion;
import com.capstone.percs.entities.PunchCard;
import com.capstone.percs.entities.User;
import com.capstone.percs.repository.BusinessRepo;
import com.capstone.percs.repository.PromotionRepo;
import com.capstone.percs.repository.PunchCardRepo;
import com.capstone.percs.repository.UserRepo;

@Controller
@RequestMapping(path = "percs") // This means URL's start with /percs (after Application path ie: localhost:8080) 
public class MainController {

	@Autowired // This means to get the bean called userRepo Which is auto-generated by Spring,
	// we will use it to handle the data
	private UserRepo userRepo;
	
	@Autowired
	private PunchCardRepo pcardRepo;

	@Autowired
	private BusinessRepo busRepo;
	
	@Autowired
	private PromotionRepo promoRepo;

	@RequestMapping("/home")
	public String home() {
		return "home";
	}
	
	@RequestMapping("/register")
	public String register() {
		return "registerLogin";
	}
	
	@RequestMapping("/request-card")
	public String registerCard() {
		return "test";
	}
	
	@RequestMapping("/businesses")
	public String businessesPage() {
		return "businesses";
	}

	
	/*
	 * ANYTHING BELOW THIS COMMENT IS TEST, INCOMPLETE, OR DEAD CODE!!!
	 */
	

}
